kind: PersistentVolume
apiVersion: v1
metadata:
  name: nn-hadoop
  labels:
    type: local
    job: kerberostest
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/nn"