kind: PersistentVolume
apiVersion: v1
metadata:
  name: server-keytab
  labels:
    type: local
    job: kerberostest
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/keytab"